export const initialData = {
  profile: {
    name: "Nathan Antenor",
    role: "Diretor Criativo & Design Specialist",
    company: "Estúdio Criativo Beta",
    cnpj: "42.891.023/0001-44",
    email: "contato@estudiocriativo.com.br",
    phone: "(11) 98765-4321",
    instagram: "@estudiocriativobeta",
    website: "https://estudiocriativobeta.com.br",
    address: "Av. Paulista, 1000 - Bela Vista, São Paulo - SP",
    currency: "BRL",
    theme: "light",
    dateFormat: "DD/MM/YYYY",
    xp: 1240,
    level: 12,
    xpEnabled: true,
    dashboardWidgets: {
      attention: true,
      finance: true,
      cashflow: true,
      commercial: true,
      health: true,
      projects: true,
      deliveries: true,
      goals: true,
      routine: true
    }
  },
  categories: [
    { id: "cat-1", name: "Serviços & Projetos", icon: "briefcase", color: "#0000FF", type: "business", nature: "income" },
    { id: "cat-2", name: "Recorrência / Retainer", icon: "repeat", color: "#10B981", type: "business", nature: "income" },
    { id: "cat-3", name: "Software & SaaS", icon: "laptop", color: "#6366F1", type: "business", nature: "expense" },
    { id: "cat-4", name: "Equipamentos & Hardware", icon: "monitor", color: "#F59E0B", type: "business", nature: "expense" },
    { id: "cat-5", name: "Internet & Telefonia", icon: "wifi", color: "#06B6D4", type: "business", nature: "expense" },
    { id: "cat-6", name: "Impostos & Tributos", icon: "file-text", color: "#EF4444", type: "business", nature: "expense" },
    { id: "cat-7", name: "Freelancers & Parceiros", icon: "users", color: "#8B5CF6", type: "business", nature: "expense" },
    { id: "cat-8", name: "Moradia & Contas", icon: "home", color: "#3B82F6", type: "personal", nature: "expense" },
    { id: "cat-9", name: "Alimentação", icon: "coffee", color: "#F97316", type: "personal", nature: "expense" },
    { id: "cat-10", name: "Saúde & Bem-estar", icon: "heart", color: "#14B8A6", type: "personal", nature: "expense" },
    { id: "cat-11", name: "Lazer & Viagens", icon: "compass", color: "#84CC16", type: "personal", nature: "expense" }
  ],
  services: [
    {
      id: "srv-1",
      name: "Identidade Visual & Branding Premium",
      description: "Construção de marca completa: diagnóstico, naming opcional, logotipo, paleta, tipografia, manual de identidade e aplicações.",
      category: "Design",
      price: 4500,
      timeline: "20 dias",
      deliverables: ["Manual de Identidade em PDF", "Logotipos em SVG/PNG", "Guia de Tipografia e Cores", "5 Mockups de Aplicação"],
      paymentTerms: "50% de entrada + 50% na aprovação final",
      status: "active"
    },
    {
      id: "srv-2",
      name: "Design de Interface UI/UX para App e Web",
      description: "Desenvolvimento de interfaces funcionais no Figma, pesquisa de usuários, prototipagem interativa e design system.",
      category: "Desenvolvimento / UI",
      price: 6800,
      timeline: "25 dias",
      deliverables: ["Protótipo interativo no Figma", "Design System com tokens", "Fluxos em alta fidelidade", "Documentação de handoff"],
      paymentTerms: "40% entrada, 30% wireframes, 30% entrega final",
      status: "active"
    },
    {
      id: "srv-3",
      name: "Gestão Completa de Social Media & Conteúdo",
      description: "Planejamento mensal de conteúdo estratégico, 12 posts feed/carrosséis, 8 reels com roteiro e edição, relatórios mensais.",
      category: "Social Media",
      price: 2400,
      timeline: "Mensal (recorrente)",
      deliverables: ["12 Posts de Feed", "8 Vídeos Reels editados", "Roteiros estratégicos semanais", "Relatório mensal de métricas"],
      paymentTerms: "Pré-pago com vencimento dia 05",
      status: "active"
    },
    {
      id: "srv-4",
      name: "Produção e Edição de Vídeo Comercial",
      description: "Produção audiovisual completa para comerciais, manifesto de marca, YouTube e campanhas institucionais.",
      category: "Audiovisual",
      price: 3800,
      timeline: "12 dias",
      deliverables: ["1 Vídeo Master 4K (60s)", "3 Cortes verticais 9:16 para Reels", "Trilha sonora licenciada", "Color grading cinematográfico"],
      paymentTerms: "50% no início + 50% após corte final",
      status: "active"
    },
    {
      id: "srv-5",
      name: "Landing Page de Alta Conversão",
      description: "Criação de landing page responsiva, ultrarrápida, orientada à conversão, com SEO otimizado e integração de WhatsApp e CRM.",
      category: "Desenvolvimento",
      price: 3500,
      timeline: "15 dias",
      deliverables: ["Página desenvolvida e responsiva", "Integração com CRM e pixel", "SEO On-page básico", "Treinamento para edição"],
      paymentTerms: "50% entrada + 50% na publicação oficial",
      status: "active"
    }
  ],
  leads: [
    {
      id: "lead-1",
      name: "Camila Rocha",
      company: "Estúdio Aurora Cerâmicas",
      phone: "(11) 97123-4567",
      email: "camila@estudioaurora.com.br",
      channel: "Instagram",
      serviceOfInterest: "Identidade Visual & Branding Premium",
      estimatedValue: 4500,
      status: "novo",
      responsible: "Nathan Antenor",
      lastContact: "2026-10-01",
      nextContact: "2026-10-03",
      createdAt: "2026-09-28",
      notes: "Lead veio via direct procurando reposicionamento para o lançamento de sua nova coleção premium."
    },
    {
      id: "lead-2",
      name: "Rodrigo Mendes",
      company: "TechVibe Startups",
      phone: "(11) 98234-5678",
      email: "rodrigo@techvibe.io",
      channel: "Indicação",
      serviceOfInterest: "Design de Interface UI/UX para App e Web",
      estimatedValue: 7800,
      status: "contato",
      responsible: "Nathan Antenor",
      lastContact: "2026-09-30",
      nextContact: "2026-10-04",
      createdAt: "2026-09-25",
      notes: "Já fez uma reunião preliminar; precisa de redesign completo do MVP antes da rodada Seed."
    },
    {
      id: "lead-3",
      name: "Beatriz Silveira",
      company: "Café Botânico",
      phone: "(21) 99345-6789",
      email: "beatriz@cafebotanico.com.br",
      channel: "Google",
      serviceOfInterest: "Gestão Completa de Social Media & Conteúdo",
      estimatedValue: 2400,
      status: "diagnostico",
      responsible: "Nathan Antenor",
      lastContact: "2026-09-29",
      nextContact: "2026-10-05",
      createdAt: "2026-09-20",
      notes: "Precisa de reels semanais e estratégia de público para abertura da nova filial."
    },
    {
      id: "lead-4",
      name: "Lucas Fontes",
      company: "Pulse Academia & Cross",
      phone: "(31) 98456-7890",
      email: "lucas@pulsefitness.com.br",
      channel: "Site",
      serviceOfInterest: "Produção e Edição de Vídeo Comercial",
      estimatedValue: 3800,
      status: "orcamento",
      responsible: "Nathan Antenor",
      lastContact: "2026-09-27",
      nextContact: "2026-10-03",
      createdAt: "2026-09-15",
      notes: "Orçamento PROP-2026-004 enviado no valor de R$ 3.800. Aguardando validação dos sócios."
    },
    {
      id: "lead-5",
      name: "Dra. Mariana Duarte",
      company: "Clínica Serena Dermatologia",
      phone: "(11) 97567-8901",
      email: "dra.mariana@clinicaserena.com.br",
      channel: "WhatsApp",
      serviceOfInterest: "Identidade Visual & Branding Premium",
      estimatedValue: 8500,
      status: "negociacao",
      responsible: "Nathan Antenor",
      lastContact: "2026-10-01",
      nextContact: "2026-10-04",
      createdAt: "2026-09-10",
      notes: "Negociando pacote de Rebranding completo com Landing Page consultiva."
    },
    {
      id: "lead-6",
      name: "Felipe Albuquerque",
      company: "Nova Construtora & Incorporadora",
      phone: "(41) 99678-9012",
      email: "felipe@novaincorporadora.com.br",
      channel: "Indicação",
      serviceOfInterest: "Identidade Visual & Branding Premium",
      estimatedValue: 6200,
      status: "aprovado",
      responsible: "Nathan Antenor",
      lastContact: "2026-09-29",
      nextContact: "2026-10-02",
      createdAt: "2026-09-05",
      notes: "Proposta aceita! Pronto para conversão em cliente formal e início imediato do projeto."
    },
    {
      id: "lead-7",
      name: "Juliana Prado",
      company: "Ateliê Florir Velas",
      phone: "(19) 98789-0123",
      email: "juliana@atelieflorir.com.br",
      channel: "Instagram",
      serviceOfInterest: "Landing Page de Alta Conversão",
      estimatedValue: 5400,
      status: "negociacao",
      responsible: "Nathan Antenor",
      lastContact: "2026-09-28",
      nextContact: "2026-10-06",
      createdAt: "2026-09-18",
      notes: "Quer incluir integração com checkout da Shopify e automação de e-mails."
    },
    {
      id: "lead-8",
      name: "Bruno Martins",
      company: "Venture Capital Partner",
      phone: "(11) 99890-1234",
      email: "bruno@vcpartner.com.br",
      channel: "LinkedIn",
      serviceOfInterest: "Identidade Visual & Branding Premium",
      estimatedValue: 2900,
      status: "cancelado",
      responsible: "Nathan Antenor",
      lastContact: "2026-09-22",
      nextContact: "",
      createdAt: "2026-09-02",
      notes: "Optou por manter equipe interna temporariamente por questões de orçamento."
    }
  ],
  clients: [
    {
      id: "cli-1",
      name: "Laura Vasconcelos",
      company: "Studio Lumina Iluminação",
      document: "33.456.789/0001-12",
      phone: "(11) 98111-2233",
      whatsapp: "(11) 98111-2233",
      email: "laura@studiolumina.com.br",
      instagram: "@studioluminadesign",
      website: "https://studiolumina.com.br",
      address: "Rua Oscar Freire, 850 - Jardins, São Paulo - SP",
      channel: "Indicação",
      entryDate: "2025-11-10",
      clientType: "mensal",
      status: "active",
      notes: "Cliente de alto valor com contrato de retainer mensal e projetos sob demanda.",
      totalGenerated: 21000,
      projectsCount: 3,
      averageTicket: 7000,
      contractFrequency: "Mensal",
      lastServiceDate: "2026-09-20",
      lastContactDate: "2026-10-01"
    },
    {
      id: "cli-2",
      name: "Carlos Eduardo Costa",
      company: "Nexo Soluções Digitais",
      document: "19.876.543/0001-99",
      phone: "(11) 97222-3344",
      whatsapp: "(11) 97222-3344",
      email: "carlos@nexosolucoes.com.br",
      instagram: "@nexosolucoes",
      website: "https://nexosolucoes.com.br",
      address: "Rua Funchal, 418 - Vila Olímpia, São Paulo - SP",
      channel: "LinkedIn",
      entryDate: "2026-01-15",
      clientType: "recorrente",
      status: "active",
      notes: "Startups em escala; parcerias contínuas para sprints de design UI/UX.",
      totalGenerated: 18200,
      projectsCount: 2,
      averageTicket: 9100,
      contractFrequency: "Bimestral",
      lastServiceDate: "2026-09-15",
      lastContactDate: "2026-09-30"
    },
    {
      id: "cli-3",
      name: "Dr. Henrique Paiva",
      company: "Clínica Paiva Odontologia",
      document: "389.452.128-09",
      phone: "(11) 98333-4455",
      whatsapp: "(11) 98333-4455",
      email: "dr.henrique@clinicapaiva.com.br",
      instagram: "@drhenriquepaiva",
      website: "https://clinicapaiva.com.br",
      address: "Av. Ibirapuera, 2030 - Moema, São Paulo - SP",
      channel: "Instagram",
      entryDate: "2026-04-10",
      clientType: "pontual",
      status: "active",
      notes: "Contratou projeto completo de rebranding e papelaria fina.",
      totalGenerated: 4800,
      projectsCount: 1,
      averageTicket: 4800,
      contractFrequency: "Pontual",
      lastServiceDate: "2026-09-25",
      lastContactDate: "2026-09-28"
    },
    {
      id: "cli-4",
      name: "Fernanda Lima",
      company: "Vanguarda Arquitetura",
      document: "28.321.654/0001-77",
      phone: "(21) 99444-5566",
      whatsapp: "(21) 99444-5566",
      email: "fernanda@vanguardaarq.com.br",
      instagram: "@vanguardaarquitetura",
      website: "https://vanguardaarq.com.br",
      address: "Rua Visconde de Pirajá, 500 - Ipanema, Rio de Janeiro - RJ",
      channel: "Indicação",
      entryDate: "2026-02-01",
      clientType: "mensal",
      status: "active",
      notes: "Contrato mensal de direção de arte, renderizações 3D conceituais e gestão de redes.",
      totalGenerated: 14000,
      projectsCount: 2,
      averageTicket: 7000,
      contractFrequency: "Mensal",
      lastServiceDate: "2026-09-28",
      lastContactDate: "2026-09-29"
    },
    {
      id: "cli-5",
      name: "Marcelo Souza",
      company: "GreenFood Produtos Orgânicos",
      document: "12.789.456/0001-33",
      phone: "(11) 98555-6677",
      whatsapp: "(11) 98555-6677",
      email: "marcelo@greenfoodorganicos.com.br",
      instagram: "@greenfoodorganicos",
      website: "https://greenfoodorganicos.com.br",
      address: "Rodovia Raposo Tavares, Km 22 - Cotia - SP",
      channel: "Google",
      entryDate: "2025-08-20",
      clientType: "inativo",
      status: "inactive",
      notes: "Sem contratação há mais de 90 dias. Oportunidade de novo serviço na linha de bebidas.",
      totalGenerated: 7500,
      projectsCount: 1,
      averageTicket: 7500,
      contractFrequency: "Pontual",
      lastServiceDate: "2026-06-28",
      lastContactDate: "2026-06-29"
    }
  ],
  proposals: [
    {
      id: "prop-1",
      number: "PROP-2026-001",
      clientId: "cli-1",
      clientName: "Laura Vasconcelos (Studio Lumina)",
      serviceId: "srv-3",
      serviceName: "Gestão Completa de Social Media & Conteúdo",
      description: "Contrato semestral de gestão de redes e produção de fotos de iluminação técnica.",
      deliverables: ["12 Posts mensais", "8 Reels com captação", "Relatório de performance"],
      value: 14400,
      discount: 400,
      finalValue: 14000,
      deadline: "6 meses",
      validity: "2026-10-15",
      paymentTerms: "6 parcelas mensais de R$ 2.333,33",
      status: "aprovada",
      createdAt: "2026-09-10",
      notes: "Proposta formal aprovada com início das gravações marcado para outubro."
    },
    {
      id: "prop-2",
      number: "PROP-2026-002",
      clientId: "cli-2",
      clientName: "Carlos Eduardo Costa (Nexo Soluções)",
      serviceId: "srv-2",
      serviceName: "Design de Interface UI/UX para App e Web",
      description: "Design System completo e fluxo de onboarding para o novo aplicativo mobile B2B.",
      deliverables: ["Design System Figma", "32 Telas em alta fidelidade", "Documentação completa de handoff"],
      value: 7500,
      discount: 300,
      finalValue: 7200,
      deadline: "25 dias",
      validity: "2026-10-12",
      paymentTerms: "50% entrada e 50% na validação do protótipo",
      status: "aprovada",
      createdAt: "2026-09-14",
      notes: "Convertido em projeto ativo de desenvolvimento de UI."
    },
    {
      id: "prop-3",
      number: "PROP-2026-003",
      clientId: null,
      clientName: "Dra. Mariana Duarte (Clínica Serena)",
      serviceId: "srv-1",
      serviceName: "Identidade Visual & Branding Premium",
      description: "Rebranding corporativo e desenvolvimento de landing page institucional.",
      deliverables: ["Manual de marca", "Papelaria", "Site responsivo"],
      value: 9000,
      discount: 500,
      finalValue: 8500,
      deadline: "30 dias",
      validity: "2026-10-10",
      paymentTerms: "Entrada de 40% + 2x de 30%",
      status: "negociacao",
      createdAt: "2026-09-22",
      notes: "Aguardando definição sobre o módulo de agendamento online."
    },
    {
      id: "prop-4",
      number: "PROP-2026-004",
      clientId: null,
      clientName: "Lucas Fontes (Pulse Academia)",
      serviceId: "srv-4",
      serviceName: "Produção e Edição de Vídeo Comercial",
      description: "Vídeo manifesto em 4K e 3 pílulas para anúncios de conversão no Meta Ads.",
      deliverables: ["1 Vídeo master 60s", "3 Cortes verticais"],
      value: 4000,
      discount: 200,
      finalValue: 3800,
      deadline: "12 dias",
      validity: "2026-10-08",
      paymentTerms: "50% no início e 50% na entrega",
      status: "enviada",
      createdAt: "2026-09-27",
      notes: "Enviado por e-mail e WhatsApp com link de apresentação em vídeo."
    },
    {
      id: "prop-5",
      number: "PROP-2026-005",
      clientId: null,
      clientName: "Bruno Martins (Venture Capital)",
      serviceId: "srv-1",
      serviceName: "Identidade Visual & Branding Premium",
      description: "Pitch deck visual e manual resumido para rodada Seed.",
      deliverables: ["Deck 15 slides no Figma", "Versão interativa PDF"],
      value: 3200,
      discount: 300,
      finalValue: 2900,
      deadline: "7 dias",
      validity: "2026-09-25",
      paymentTerms: "À vista com desconto",
      status: "recusada",
      createdAt: "2026-09-12",
      notes: "Cliente postergou a captação para o próximo trimestre."
    },
    {
      id: "prop-6",
      number: "PROP-2026-006",
      clientId: null,
      clientName: "Juliana Prado (Ateliê Florir)",
      serviceId: "srv-5",
      serviceName: "Landing Page de Alta Conversão",
      description: "E-commerce de velas aromáticas artesanais com catálogo visual refinado.",
      deliverables: ["Loja virtual montada", "Guia de boas práticas", "Checkout ativo"],
      value: 5400,
      discount: 0,
      finalValue: 5400,
      deadline: "15 dias",
      validity: "2026-10-20",
      paymentTerms: "3x no cartão de crédito",
      status: "rascunho",
      createdAt: "2026-10-01",
      notes: "Rascunho inicial em elaboração com base no briefing coletado."
    }
  ],
  projects: [
    {
      id: "proj-1",
      title: "Redesign de Identidade Visual & Aplicações",
      clientId: "cli-1",
      clientName: "Studio Lumina Iluminação",
      serviceId: "srv-1",
      serviceName: "Identidade Visual & Branding Premium",
      value: 4500,
      stage: "em_andamento",
      priority: "alta",
      startDate: "2026-09-18",
      deadlineDate: "2026-10-16",
      responsible: "Nathan Antenor",
      notes: "Desenvolvimento dos conceitos de marca com foco em sofisticação minimalista.",
      tasks: [
        { id: "pt-1", title: "Mapeamento de referências e benchmarking", completed: true },
        { id: "pt-2", title: "Definição do grid construtivo e símbolo", completed: true },
        { id: "pt-3", title: "Seleção tipográfica e paleta cromática", completed: true },
        { id: "pt-4", title: "Criação de mockups de aplicação em luminárias", completed: false },
        { id: "pt-5", title: "Montagem da apresentação de defesa do conceito", completed: false }
      ]
    },
    {
      id: "proj-2",
      title: "Design de Interface Web App & Mobile Nexo",
      clientId: "cli-2",
      clientName: "Nexo Soluções Digitais",
      serviceId: "srv-2",
      serviceName: "Design de Interface UI/UX para App e Web",
      value: 7200,
      stage: "revisao",
      priority: "alta",
      startDate: "2026-09-12",
      deadlineDate: "2026-10-07",
      responsible: "Nathan Antenor",
      notes: "Protótipo navegável em fase de validação com os usuários-chave e PO.",
      tasks: [
        { id: "pt-6", title: "Estrutura de arquitetura da informação", completed: true },
        { id: "pt-7", title: "Wireframes de média fidelidade", completed: true },
        { id: "pt-8", title: "Design System com tokens e variantes", completed: true },
        { id: "pt-9", title: "Revisão e ajuste dos fluxos de pagamento", completed: false }
      ]
    },
    {
      id: "proj-3",
      title: "Vídeo Institucional Comercial",
      clientId: "cli-1",
      clientName: "Pulse Academia & Cross",
      serviceId: "srv-4",
      serviceName: "Produção e Edição de Vídeo Comercial",
      value: 3800,
      stage: "briefing",
      priority: "media",
      startDate: "2026-10-01",
      deadlineDate: "2026-10-22",
      responsible: "Nathan Antenor",
      notes: "Definindo locações e atores para gravação das cenas de ação.",
      tasks: [
        { id: "pt-10", title: "Reunião de alinhamento de roteiro", completed: true },
        { id: "pt-11", title: "Storyboard e plano de filmagem", completed: false },
        { id: "pt-12", title: "Gravação das cenas principais", completed: false }
      ]
    },
    {
      id: "proj-4",
      title: "Identidade Visual & Papelaria Fina",
      clientId: "cli-3",
      clientName: "Dr. Henrique Paiva",
      serviceId: "srv-1",
      serviceName: "Identidade Visual & Branding Premium",
      value: 4800,
      stage: "entrega",
      priority: "urgente",
      startDate: "2026-09-01",
      deadlineDate: "2026-10-04",
      responsible: "Nathan Antenor",
      notes: "Arquivos finais prontos e testados. Agendada reunião de hand-off dos vetores.",
      tasks: [
        { id: "pt-13", title: "Criação de símbolo e logotipo", completed: true },
        { id: "pt-14", title: "Manual de aplicação em jaleco e placas", completed: true },
        { id: "pt-15", title: "Preparação de arquivos para gráfica (CMYK/Pantone)", completed: true },
        { id: "pt-16", title: "Envio de pasta final na nuvem e backup", completed: true }
      ]
    },
    {
      id: "proj-5",
      title: "Campanhas Visuais & Redes Sociais Q3",
      clientId: "cli-4",
      clientName: "Vanguarda Arquitetura",
      serviceId: "srv-3",
      serviceName: "Gestão Completa de Social Media & Conteúdo",
      value: 3500,
      stage: "finalizacao",
      priority: "media",
      startDate: "2026-09-05",
      deadlineDate: "2026-10-10",
      responsible: "Nathan Antenor",
      notes: "Aprovação do pacote mensal de renders e posts sobre a Casa da Serra.",
      tasks: [
        { id: "pt-17", title: "Roteirização de vídeos com os arquitetos", completed: true },
        { id: "pt-18", title: "Edição de 6 Reels de antes/depois da obra", completed: true },
        { id: "pt-19", title: "Programação e publicação das mídias", completed: false }
      ]
    }
  ],
  transactions: [
    {
      id: "tx-1",
      title: "Mensalidade Gestão de Marca - Studio Lumina",
      type: "income",
      scope: "business",
      amount: 3500,
      category: "Recorrência / Retainer",
      subCategory: "Social Media",
      date: "2026-10-01",
      dueDate: "2026-10-01",
      paymentDate: "2026-10-01",
      clientId: "cli-1",
      projectId: "proj-1",
      paymentMethod: "Pix",
      account: "Banco Inter PJ",
      recurrence: "monthly",
      status: "paid",
      notes: "Pagamento referente à mensalidade do mês de outubro."
    },
    {
      id: "tx-2",
      title: "Entrada UI/UX App - Nexo Soluções",
      type: "income",
      scope: "business",
      amount: 3600,
      category: "Serviços & Projetos",
      subCategory: "UI Design",
      date: "2026-09-15",
      dueDate: "2026-09-15",
      paymentDate: "2026-09-15",
      clientId: "cli-2",
      projectId: "proj-2",
      paymentMethod: "Transferência",
      account: "Banco Inter PJ",
      recurrence: "none",
      status: "paid",
      notes: "Primeira parcela (50%) aprovada conforme proposta comercial."
    },
    {
      id: "tx-3",
      title: "Parcela Final Identidade Visual - Dr. Henrique Paiva",
      type: "income",
      scope: "business",
      amount: 2400,
      category: "Serviços & Projetos",
      subCategory: "Branding",
      date: "2026-09-28",
      dueDate: "2026-09-28",
      paymentDate: "2026-09-28",
      clientId: "cli-3",
      projectId: "proj-4",
      paymentMethod: "Pix",
      account: "Banco Inter PJ",
      recurrence: "none",
      status: "paid",
      notes: "Pagamento de quitação na conclusão das peças gráficas."
    },
    {
      id: "tx-4",
      title: "Retainer Mensal - Vanguarda Arquitetura",
      type: "income",
      scope: "business",
      amount: 3500,
      category: "Recorrência / Retainer",
      subCategory: "Audiovisual",
      date: "2026-09-25",
      dueDate: "2026-09-25",
      paymentDate: "2026-09-25",
      clientId: "cli-4",
      projectId: "proj-5",
      paymentMethod: "Pix",
      account: "Banco Inter PJ",
      recurrence: "monthly",
      status: "paid",
      notes: "Ciclo mensal de produção de conteúdo arquitetônico."
    },
    {
      id: "tx-5",
      title: "Assinatura Adobe Creative Cloud & Figma Pro",
      type: "expense",
      scope: "business",
      amount: 340,
      category: "Software & SaaS",
      subCategory: "Ferramentas de Design",
      date: "2026-09-20",
      dueDate: "2026-09-20",
      paymentDate: "2026-09-20",
      clientId: null,
      projectId: null,
      paymentMethod: "Cartão de Crédito",
      account: "Nubank PJ",
      recurrence: "monthly",
      status: "paid",
      notes: "Assinaturas essenciais de ferramentas de trabalho."
    },
    {
      id: "tx-6",
      title: "Servidor Web, Domínios & Hospedagem AWS",
      type: "expense",
      scope: "business",
      amount: 180,
      category: "Internet & Telefonia",
      subCategory: "Hospedagem",
      date: "2026-09-18",
      dueDate: "2026-09-18",
      paymentDate: "2026-09-18",
      clientId: null,
      projectId: null,
      paymentMethod: "Cartão de Crédito",
      account: "Nubank PJ",
      recurrence: "monthly",
      status: "paid",
      notes: "Hospedagem das páginas dos clientes e do portfólio."
    },
    {
      id: "tx-7",
      title: "Aluguel e Condomínio do Estúdio",
      type: "expense",
      scope: "personal",
      amount: 2100,
      category: "Moradia & Contas",
      subCategory: "Aluguel",
      date: "2026-10-01",
      dueDate: "2026-10-05",
      paymentDate: "2026-10-01",
      clientId: null,
      projectId: null,
      paymentMethod: "Boleto",
      account: "Itaú PF",
      recurrence: "monthly",
      status: "paid",
      notes: "Despesa fixa mensal de moradia / home office."
    },
    {
      id: "tx-8",
      title: "Plano de Saúde e Prevenção",
      type: "expense",
      scope: "personal",
      amount: 480,
      category: "Saúde & Bem-estar",
      subCategory: "Convênio",
      date: "2026-09-28",
      dueDate: "2026-09-28",
      paymentDate: "2026-09-28",
      clientId: null,
      projectId: null,
      paymentMethod: "Débito Automático",
      account: "Itaú PF",
      recurrence: "monthly",
      status: "paid",
      notes: "Plano médico individual."
    }
  ],
  tasks: [
    {
      id: "task-1",
      title: "Exportar arquivos finais em vetor (SVG/EPS) para Dr. Henrique",
      priority: "urgente",
      status: "in_progress",
      dueDate: "2026-10-03",
      clientId: "cli-3",
      projectId: "proj-4",
      notes: "Conferir separação de cores e fontes convertidas em curvas."
    },
    {
      id: "task-2",
      title: "Apresentar primeira versão dos wireframes para Nexo Soluções",
      priority: "alta",
      status: "todo",
      dueDate: "2026-10-04",
      clientId: "cli-2",
      projectId: "proj-2",
      notes: "Preparar protótipo de clique interativo no Figma."
    },
    {
      id: "task-3",
      title: "Montar briefing e roteiro técnico do vídeo da Pulse Academia",
      priority: "media",
      status: "todo",
      dueDate: "2026-10-05",
      clientId: null,
      projectId: "proj-3",
      notes: "Definir horários de iluminação ideal no espaço de treino."
    },
    {
      id: "task-4",
      title: "Agendar postagens e carrosséis semanais da Studio Lumina",
      priority: "alta",
      status: "in_progress",
      dueDate: "2026-10-03",
      clientId: "cli-1",
      projectId: "proj-1",
      notes: "Verificar legendas com links para a nova coleção."
    },
    {
      id: "task-5",
      title: "Emitir nota fiscal e recibo mensal Vanguarda Arquitetura",
      priority: "media",
      status: "todo",
      dueDate: "2026-10-06",
      clientId: "cli-4",
      projectId: "proj-5",
      notes: "Enviar PDF para o financeiro da Fernanda."
    },
    {
      id: "task-6",
      title: "Revisar métricas de tráfego e relatórios de conversão do mês",
      priority: "baixa",
      status: "todo",
      dueDate: "2026-10-08",
      clientId: null,
      projectId: null,
      notes: "Consolidar dados para a apresentação interna."
    }
  ],
  habits: [
    {
      id: "hbt-1",
      name: "Leitura Técnica e Design",
      target: "20 min/dia",
      frequency: "daily",
      streak: 14,
      bestStreak: 28,
      consistencyRate: 88,
      completedToday: true,
      category: "Educação"
    },
    {
      id: "hbt-2",
      name: "Estudo de Ferramentas & IA",
      target: "30 min/dia",
      frequency: "daily",
      streak: 7,
      bestStreak: 12,
      consistencyRate: 75,
      completedToday: true,
      category: "Tecnologia"
    },
    {
      id: "hbt-3",
      name: "Treino e Exercício Físico",
      target: "45 min (4x sem)",
      frequency: "custom",
      streak: 5,
      bestStreak: 21,
      consistencyRate: 80,
      completedToday: false,
      category: "Saúde"
    },
    {
      id: "hbt-4",
      name: "Organização Financeira & Inbox Zero",
      target: "10 min no final do dia",
      frequency: "daily",
      streak: 19,
      bestStreak: 19,
      consistencyRate: 95,
      completedToday: true,
      category: "Produtividade"
    }
  ],
  goals: [
    {
      id: "goal-1",
      title: "Faturamento Mensal Outubro",
      scope: "business",
      category: "Receita",
      targetValue: 30000,
      currentValue: 13000,
      deadline: "2026-10-31",
      priority: "alta",
      status: "in_progress",
      linkedCategory: "Serviços & Projetos",
      notes: "Meta para ultrapassar o recorde anterior com a entrada de novos projetos."
    },
    {
      id: "goal-2",
      title: "Reserva de Emergência PJ",
      scope: "business",
      category: "Segurança",
      targetValue: 50000,
      currentValue: 32500,
      deadline: "2026-12-31",
      priority: "alta",
      status: "in_progress",
      linkedCategory: "Recorrência / Retainer",
      notes: "Manter pelo menos 6 meses de custos fixos operacionais guardados."
    },
    {
      id: "goal-3",
      title: "Upgrade Estúdio (Monitor 4K & Câmera)",
      scope: "business",
      category: "Equipamentos",
      targetValue: 15000,
      currentValue: 9000,
      deadline: "2026-11-30",
      priority: "media",
      status: "in_progress",
      linkedCategory: "Equipamentos & Hardware",
      notes: "Melhoria de setup para gravação de vídeos institucionais."
    },
    {
      id: "goal-4",
      title: "Viagem de Férias e Descanso",
      scope: "personal",
      category: "Lazer",
      targetValue: 12000,
      currentValue: 7200,
      deadline: "2027-01-15",
      priority: "media",
      status: "in_progress",
      linkedCategory: "Lazer & Viagens",
      notes: "Férias programadas com a família no litoral."
    }
  ],
  events: [
    {
      id: "evt-1",
      title: "Reunião de Alinhamento e Wireframes",
      date: "2026-10-02",
      startTime: "14:00",
      endTime: "15:00",
      clientId: "cli-2",
      projectId: "proj-2",
      location: "Google Meet",
      participants: "Nathan Antenor, Carlos Eduardo",
      notes: "Apresentação dos fluxos de navegação e aprovação do protótipo.",
      syncedWithGoogle: true
    },
    {
      id: "evt-2",
      title: "Diagnóstico e Briefing de Marca",
      date: "2026-10-03",
      startTime: "10:00",
      endTime: "11:30",
      clientId: null,
      projectId: null,
      location: "Vídeo Chamada",
      participants: "Nathan Antenor, Camila Rocha",
      notes: "Elaboração do diagnóstico criativo da Cerâmica Aurora.",
      syncedWithGoogle: true
    },
    {
      id: "evt-3",
      title: "Gravação Externa de Cenas",
      date: "2026-10-05",
      startTime: "09:00",
      endTime: "13:00",
      clientId: null,
      projectId: "proj-3",
      location: "Pulse Academia - Unidade Jardins",
      participants: "Nathan Antenor, Lucas Fontes",
      notes: "Gravação das aulas coletivas e musculação.",
      syncedWithGoogle: false
    },
    {
      id: "evt-4",
      title: "Revisão Semanal de Produtividade & Caixa",
      date: "2026-10-02",
      startTime: "17:30",
      endTime: "18:00",
      clientId: null,
      projectId: null,
      location: "Escritório",
      participants: "Nathan Antenor",
      notes: "Fechamento semanal das contas a receber.",
      syncedWithGoogle: true
    }
  ],
  documents: [
    {
      id: "doc-1",
      name: "Contrato_Prestacao_Servicos_Studio_Lumina.pdf",
      category: "Contratos",
      size: "1.4 MB",
      format: "pdf",
      uploadDate: "2026-09-12",
      clientId: "cli-1",
      clientName: "Studio Lumina Iluminação",
      projectId: "proj-1",
      projectName: "Redesign de Identidade Visual & Aplicações",
      url: "#"
    },
    {
      id: "doc-2",
      name: "Manual_Marca_Studio_Lumina_v1.pdf",
      category: "Identidade visual",
      size: "14.8 MB",
      format: "pdf",
      uploadDate: "2026-09-20",
      clientId: "cli-1",
      clientName: "Studio Lumina Iluminação",
      projectId: "proj-1",
      projectName: "Redesign de Identidade Visual & Aplicações",
      url: "#"
    },
    {
      id: "doc-3",
      name: "Briefing_e_Arquitetura_Informacao_Nexo.pdf",
      category: "Briefings",
      size: "2.1 MB",
      format: "pdf",
      uploadDate: "2026-09-14",
      clientId: "cli-2",
      clientName: "Nexo Soluções Digitais",
      projectId: "proj-2",
      projectName: "Design de Interface Web App & Mobile Nexo",
      url: "#"
    },
    {
      id: "doc-4",
      name: "Roteiro_Comercial_60s_Pulse.pdf",
      category: "Briefings",
      size: "820 KB",
      format: "pdf",
      uploadDate: "2026-09-28",
      clientId: null,
      clientName: "Pulse Academia & Cross",
      projectId: "proj-3",
      projectName: "Vídeo Institucional Comercial",
      url: "#"
    },
    {
      id: "doc-5",
      name: "Nota_Fiscal_Eletronica_0428_Vanguarda.pdf",
      category: "Notas fiscais",
      size: "340 KB",
      format: "pdf",
      uploadDate: "2026-09-25",
      clientId: "cli-4",
      clientName: "Vanguarda Arquitetura",
      projectId: "proj-5",
      projectName: "Campanhas Visuais & Redes Sociais Q3",
      url: "#"
    },
    {
      id: "doc-6",
      name: "Pacote_Vetores_Finais_DrHenrique.zip",
      category: "Arquivos finais",
      size: "32.5 MB",
      format: "zip",
      uploadDate: "2026-10-01",
      clientId: "cli-3",
      clientName: "Dr. Henrique Paiva",
      projectId: "proj-4",
      projectName: "Identidade Visual & Papelaria Fina",
      url: "#"
    }
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Entrega Próxima do Prazo",
      message: "O projeto 'Identidade Visual & Papelaria Fina' vence em 2 dias.",
      type: "warning",
      link: "projects",
      read: false,
      createdAt: "2026-10-02 08:30"
    },
    {
      id: "notif-2",
      title: "Oportunidade de Contratação",
      message: "GreenFood Orgânicos está sem contratação há mais de 90 dias.",
      type: "info",
      link: "clients",
      read: false,
      createdAt: "2026-10-01 11:00"
    },
    {
      id: "notif-3",
      title: "Proposta Próxima do Vencimento",
      message: "A proposta PROP-2026-004 vence em breve.",
      type: "warning",
      link: "proposals",
      read: false,
      createdAt: "2026-09-30 16:45"
    },
    {
      id: "notif-4",
      title: "Meta Financeira em Avanço",
      message: "Você já atingiu 43% da meta 'Faturamento Mensal Outubro'!",
      type: "success",
      link: "goals",
      read: true,
      createdAt: "2026-10-01 18:00"
    }
  ],
  deliveryColumns: [
    { id: "backlog", title: "Backlog", color: "border-zinc-400" },
    { id: "em_andamento", title: "Em andamento", color: "border-blue-500" },
    { id: "em_revisao", title: "Em revisão", color: "border-amber-500" },
    { id: "aprovado", title: "Aprovado", color: "border-purple-500" },
    { id: "entregue", title: "Entregue", color: "border-emerald-500" },
    { id: "pausado", title: "Pausado", color: "border-zinc-500" }
  ],
  deliveryTags: [
    { id: "tag-1", name: "Design", color: "#3B82F6" },
    { id: "tag-2", name: "Social Media", color: "#EC4899" },
    { id: "tag-3", name: "Vídeo", color: "#8B5CF6" },
    { id: "tag-4", name: "UI/UX", color: "#10B981" },
    { id: "tag-5", name: "Urgente", color: "#EF4444" },
    { id: "tag-6", name: "Copywriting", color: "#F59E0B" }
  ],
  deliveries: [
    {
      id: "del-1",
      title: "Post Campanha de Matrícula",
      clientId: "cli-1",
      clientName: "Studio Lumina Iluminação",
      projectId: "proj-1",
      projectName: "Redesign de Identidade Visual & Aplicações",
      status: "em_andamento",
      priority: "alta",
      coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
      dueDate: "2026-10-10",
      assignee: "Nathan Antenor",
      tags: ["Design", "Social Media"],
      description: "Criação de post em carrossel e estático com foco na conversão para nova turma e captação de leads qualificados.",
      checklist: [
        { id: "c-1", title: "Criação do conceito visual 3D", completed: true },
        { id: "c-2", title: "Redação de copy persuasiva", completed: true },
        { id: "c-3", title: "Aprovação interna do diretor de arte", completed: true },
        { id: "c-4", title: "Exportação dos formatos 1:1 e 9:16", completed: false },
        { id: "c-5", title: "Envio para aprovação no portal", completed: false }
      ],
      files: [
        { id: "f-1", name: "Mockup_Campanha_v1.png", size: "2.4 MB", type: "png", date: "2026-10-01", uploader: "Nathan" }
      ],
      comments: [
        { id: "com-1", author: "Nathan Antenor", date: "2026-10-01", time: "14:30", text: "Conceito aprovado pelo cliente, finalizando os recortes." }
      ],
      history: [
        { id: "h-1", date: "2026-09-30 10:00", text: "Entrega criada no Backlog." },
        { id: "h-2", date: "2026-10-01 11:20", text: "Você moveu a entrega de Backlog para Em andamento." }
      ],
      createdAt: "2026-09-30",
      updatedAt: "2026-10-01"
    },
    {
      id: "del-2",
      title: "Design System Tokens & Componentes App",
      clientId: "cli-2",
      clientName: "Nexo Soluções Digitais",
      projectId: "proj-2",
      projectName: "Design de Interface Web App & Mobile Nexo",
      status: "em_revisao",
      priority: "alta",
      coverImage: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80",
      dueDate: "2026-10-04",
      assignee: "Nathan Antenor",
      tags: ["UI/UX", "Design"],
      description: "Padronização completa de tokens de espaçamento, tipografia, cores e componentes essenciais da interface.",
      checklist: [
        { id: "c-6", title: "Definição de cores e tipografia no Figma", completed: true },
        { id: "c-7", title: "Componentes de Botões, Inputs e Modais", completed: true },
        { id: "c-8", title: "Documentação de tokens para desenvolvedores", completed: true },
        { id: "c-9", title: "Validação com equipe de front-end", completed: false }
      ],
      files: [
        { id: "f-2", name: "Tokens_Design_System_Nexo.fig", size: "8.1 MB", type: "fig", date: "2026-09-29", uploader: "Nathan" }
      ],
      comments: [
        { id: "com-2", author: "Carlos Eduardo", date: "2026-09-30", time: "16:00", text: "Revisando os estados de hover e active nos botões." }
      ],
      history: [
        { id: "h-3", date: "2026-09-28 09:00", text: "Entrega criada." },
        { id: "h-4", date: "2026-10-01 15:40", text: "Você moveu a entrega de Em andamento para Em revisão." }
      ],
      createdAt: "2026-09-28",
      updatedAt: "2026-10-01"
    },
    {
      id: "del-3",
      title: "Roteiro Técnico & Storyboard 60s",
      clientId: "cli-1",
      clientName: "Pulse Academia & Cross",
      projectId: "proj-3",
      projectName: "Vídeo Institucional Comercial",
      status: "aprovado",
      priority: "media",
      coverImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80",
      dueDate: "2026-10-05",
      assignee: "Nathan Antenor",
      tags: ["Vídeo", "Copywriting"],
      description: "Estruturação das cenas dinâmicas com marcação de tempo para locução e efeitos sonoros.",
      checklist: [
        { id: "c-10", title: "Estrutura dos 3 atos do vídeo", completed: true },
        { id: "c-11", title: "Roteiro de locução em voz off", completed: true },
        { id: "c-12", title: "Validação pelo diretor da academia", completed: true }
      ],
      files: [
        { id: "f-3", name: "Storyboard_Pulse_vFinal.pdf", size: "3.5 MB", type: "pdf", date: "2026-09-29", uploader: "Nathan" }
      ],
      comments: [],
      history: [
        { id: "h-5", date: "2026-09-29 11:00", text: "Roteiro aprovado sem ressalvas!" }
      ],
      createdAt: "2026-09-25",
      updatedAt: "2026-09-29"
    },
    {
      id: "del-4",
      title: "Fechamento de Arquivos Gráficos (Jaleco & Papelaria)",
      clientId: "cli-3",
      clientName: "Dr. Henrique Paiva",
      projectId: "proj-4",
      projectName: "Identidade Visual & Papelaria Fina",
      status: "entregue",
      priority: "urgente",
      coverImage: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&auto=format&fit=crop&q=80",
      dueDate: "2026-10-02",
      assignee: "Nathan Antenor",
      tags: ["Design", "Urgente"],
      description: "Arquivos finais prontos em vetor CMYK e separação de cor Pantone para bordado em jaleco e gráfica rápida.",
      checklist: [
        { id: "c-13", title: "Conversão em curvas (CMYK/Pantone)", completed: true },
        { id: "c-14", title: "Gabarito de impressão de cartões e envelopes", completed: true },
        { id: "c-15", title: "Envio de link de download direto para o cliente", completed: true }
      ],
      files: [
        { id: "f-4", name: "Papelaria_Pronta_Grafica.zip", size: "45.2 MB", type: "zip", date: "2026-10-01", uploader: "Nathan" }
      ],
      comments: [
        { id: "com-3", author: "Dr. Henrique Paiva", date: "2026-10-02", time: "09:15", text: "Arquivos recebidos e aprovados pela gráfica! Muito obrigado Nathan!" }
      ],
      history: [
        { id: "h-6", date: "2026-10-02 08:30", text: "Você moveu a entrega para Entregue." }
      ],
      createdAt: "2026-09-20",
      updatedAt: "2026-10-02",
      completedAt: "2026-10-02"
    },
    {
      id: "del-5",
      title: "Carrossel Instagram: Destaques da Casa da Serra",
      clientId: "cli-4",
      clientName: "Vanguarda Arquitetura",
      projectId: "proj-5",
      projectName: "Campanhas Visuais & Redes Sociais Q3",
      status: "em_andamento",
      priority: "media",
      coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80",
      dueDate: "2026-10-06",
      assignee: "Nathan Antenor",
      tags: ["Social Media", "Design"],
      description: "Carrossel de 8 lâminas mostrando os detalhes de marcenaria e iluminação natural do projeto premiado.",
      checklist: [
        { id: "c-16", title: "Seleção das 7 melhores fotos da obra", completed: true },
        { id: "c-17", title: "Tratamento de cor e aplicação de template", completed: true },
        { id: "c-18", title: "Texto explicativo dos materiais nobres", completed: false }
      ],
      files: [],
      comments: [],
      history: [
        { id: "h-7", date: "2026-10-01 14:00", text: "Entrega em produção." }
      ],
      createdAt: "2026-09-28",
      updatedAt: "2026-10-01"
    },
    {
      id: "del-6",
      title: "Wireframes do Fluxo de Checkout & Assinatura",
      clientId: "cli-2",
      clientName: "Nexo Soluções Digitais",
      projectId: "proj-2",
      projectName: "Design de Interface Web App & Mobile Nexo",
      status: "backlog",
      priority: "alta",
      coverImage: "",
      dueDate: "2026-10-14",
      assignee: "Nathan Antenor",
      tags: ["UI/UX"],
      description: "Arquitetura da jornada de pagamento, upsell e tela de confirmação de pedido.",
      checklist: [
        { id: "c-19", title: "Benchmark de fluxos Stripe/Pagarme", completed: false },
        { id: "c-20", title: "Mapeamento das telas de erro e sucesso", completed: false }
      ],
      files: [],
      comments: [],
      history: [
        { id: "h-8", date: "2026-10-01 10:00", text: "Entrega cadastrada no Backlog do projeto." }
      ],
      createdAt: "2026-10-01",
      updatedAt: "2026-10-01"
    },
    {
      id: "del-7",
      title: "Manual de Uso e Aplicação da Marca (PDF Interativo)",
      clientId: "cli-1",
      clientName: "Studio Lumina Iluminação",
      projectId: "proj-1",
      projectName: "Redesign de Identidade Visual & Aplicações",
      status: "em_revisao",
      priority: "alta",
      coverImage: "https://images.unsplash.com/photo-1542744094-24638eff58bb?w=600&auto=format&fit=crop&q=80",
      dueDate: "2026-10-08",
      assignee: "Nathan Antenor",
      tags: ["Design", "Copywriting"],
      description: "Manual completo com 32 páginas detalhando todas as regras de aplicação em mídias físicas e digitais.",
      checklist: [
        { id: "c-21", title: "Diagramação do manual no InDesign", completed: true },
        { id: "c-22", title: "Regras de área de não interferência", completed: true },
        { id: "c-23", title: "Revisão ortográfica e links", completed: true },
        { id: "c-24", title: "Validação final da Laura", completed: false }
      ],
      files: [],
      comments: [],
      history: [
        { id: "h-9", date: "2026-10-01 18:00", text: "Movido para Em revisão." }
      ],
      createdAt: "2026-09-22",
      updatedAt: "2026-10-01"
    },
    {
      id: "del-8",
      title: "Vinheta Animada em Motion Graphics (5s)",
      clientId: "cli-1",
      clientName: "Pulse Academia & Cross",
      projectId: "proj-3",
      projectName: "Vídeo Institucional Comercial",
      status: "pausado",
      priority: "baixa",
      coverImage: "",
      dueDate: "2026-10-25",
      assignee: "Nathan Antenor",
      tags: ["Vídeo"],
      description: "Logo sting de encerramento em loop com efeitos sonoros sintéticos.",
      checklist: [
        { id: "c-25", title: "Animação da logo no After Effects", completed: true },
        { id: "c-26", title: "Efeito sonoro / Sound Design", completed: false }
      ],
      files: [],
      comments: [
        { id: "com-4", author: "Nathan Antenor", date: "2026-10-01", time: "16:00", text: "Pausado aguardando definição da nova paleta de som da Pulse." }
      ],
      history: [
        { id: "h-10", date: "2026-10-01 16:00", text: "Status alterado para Pausado." }
      ],
      createdAt: "2026-09-27",
      updatedAt: "2026-10-01"
    }
  ],
  inbox: [
    {
      id: "inb-1",
      text: "Enviar identidade visual do IBMR amanhã até às 15h para validação do comitê",
      createdAt: "2026-10-02 09:30",
      status: "pending",
      suggestedType: "delivery"
    },
    {
      id: "inb-2",
      text: "Ligar para Camila do Estúdio Aurora sobre alinhamento de contrato de branding",
      createdAt: "2026-10-02 10:15",
      status: "pending",
      suggestedType: "task"
    },
    {
      id: "inb-3",
      text: "Agendar call com Juliana sobre checkout Shopify e integrações de e-mail marketing",
      createdAt: "2026-10-02 11:00",
      status: "pending",
      suggestedType: "event"
    },
    {
      id: "inb-4",
      text: "Ideia: Criar pacote de Design System Express para startups em estágio inicial",
      createdAt: "2026-10-02 11:45",
      status: "pending",
      suggestedType: "note"
    }
  ]
};
